[theme]
primaryColor = "#FF6600"  # KNVB Orange
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for contrast
textColor = "#000000"  # Black for strong contrast
font = "sans serif"
